ARG BASE_IMAGE="ros2:dashing"
FROM ${BASE_IMAGE}

ARG TF_VERSION="2.0.0"

USER ros2

SHELL ["/bin/bash", "-c"]

RUN pip3 install pip setuptools && \
    pip3 install tensorflow==${TF_VERSION}

USER root
WORKDIR /root
ENV LANG=C.UTF-8
COPY ./entrypoint.sh /tmp/entrypoint.sh
ENTRYPOINT [ "/tmp/entrypoint.sh" ]
